# Generated by Django 2.0.3 on 2018-04-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagesurl',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
