# Generated by Django 2.0.3 on 2018-04-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180412_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usertype',
            new_name='user_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='imagesurl',
        ),
        migrations.AddField(
            model_name='user',
            name='images_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
